<?php

namespace AppBundle\Repository;

/**
 * EntradasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntradasRepository extends \Doctrine\ORM\EntityRepository
{
}
